In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("complaints.csv/complaints.csv")

C:\Users\Ryanl\AppData\Local\Temp\ipykernel_24880\3241862011.py:1: DtypeWarning: Columns (0: Consumer complaint narrative) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("complaints.csv/complaints.csv")

In [3]:
pd.set_option('display.max_rows', None)

In [4]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2023-03-24T04:36:20.000Z,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Collected or attempted to collect exempt funds,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22406,Servicemember,Web,2023-03-24T05:01:41.000Z,Closed with explanation,No,6747064.0
1,2024-02-26T22:23:15.000Z,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Sued you without properly notifying you of law...,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22042,NaN,Web,2024-03-04T18:31:15.000Z,Closed with explanation,No,8424458.0
2,2024-02-28T03:49:51.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PR,00976,NaN,Web,2024-02-28T03:54:30.000Z,Closed with non-monetary relief,Yes,8434350.0
3,2024-02-28T03:47:32.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PR,00976,NaN,Web,2024-02-28T03:53:46.000Z,Closed with explanation,Yes,8434243.0
4,2024-04-13T04:08:31.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",PR,00976,NaN,Web,2024-04-13T04:14:18.000Z,Closed with non-monetary relief,Yes,8758513.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16505480 entries, 0 to 16505479
Data columns (total 16 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 str
 1   Product                       str
 2   Sub-product                   str
 3   Issue                         str
 4   Sub-issue                     str
 5   Consumer complaint narrative  str
 6   Company public response       str
 7   Company                       str
 8   State                         str
 9   ZIP code                      str
 10  Tags                          str
 11  Submitted via                 str
 12  Date sent to company          str
 13  Company response to consumer  str
 14  Timely response?              str
 15  Complaint ID                  float64
dtypes: float64(1), str(15)
memory usage: 9.9 GB

# Deduplicate

In [6]:
df["Complaint ID"].is_unique

False

In [7]:
dupes = df[df["Complaint ID"].duplicated(keep=False)].sort_values("Complaint ID")

In [8]:
# dupes

In [9]:
dupes["Complaint ID"].unique()

array([nan])

<!-- # solution
Allow the complaint to exist along with the other features that are collected , but flag it -->

In [10]:
df_temp = df.copy()

In [11]:
df_temp["Missing Complaint ID"] = df_temp["Complaint ID"].isna()

In [12]:
# df_temp[df_temp["Complaint ID"].isna()].head()

# Date received

## Date utility

In [13]:
df_date = df.copy()

In [14]:
df_date["Date received"].head()

0    2023-03-24T04:36:20.000Z
1    2024-02-26T22:23:15.000Z
2    2024-02-28T03:49:51.000Z
3    2024-02-28T03:47:32.000Z
4    2024-04-13T04:08:31.000Z
Name: Date received, dtype: str

In [15]:
import pandas as pd


def convert_column_to_datetime(
    df: pd.DataFrame,
    column: str,
) -> None:
    """Convert mixed ISO 8601 strings to UTC datetimes in place.

    Date-only values are interpreted as midnight UTC.
    Invalid non-null values raise ValueError.
    """
    df[column] = pd.to_datetime(
        df[column],
        format="mixed",
        errors="raise",
        utc=True,
    )

    return df

In [16]:
df_date = convert_column_to_datetime(df_date, "Date received")

In [17]:
df_date.info()

<class 'pandas.DataFrame'>
RangeIndex: 16505480 entries, 0 to 16505479
Data columns (total 16 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 datetime64[us, UTC]
 1   Product                       str
 2   Sub-product                   str
 3   Issue                         str
 4   Sub-issue                     str
 5   Consumer complaint narrative  str
 6   Company public response       str
 7   Company                       str
 8   State                         str
 9   ZIP code                      str
 10  Tags                          str
 11  Submitted via                 str
 12  Date sent to company          str
 13  Company response to consumer  str
 14  Timely response?              str
 15  Complaint ID                  float64
dtypes: datetime64[us, UTC](1), float64(1), str(14)
memory usage: 9.7 GB

In [18]:
df_date.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2023-03-24 04:36:20+00:00,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Collected or attempted to collect exempt funds,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22406,Servicemember,Web,2023-03-24T05:01:41.000Z,Closed with explanation,No,6747064.0
1,2024-02-26 22:23:15+00:00,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Sued you without properly notifying you of law...,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22042,NaN,Web,2024-03-04T18:31:15.000Z,Closed with explanation,No,8424458.0
2,2024-02-28 03:49:51+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PR,00976,NaN,Web,2024-02-28T03:54:30.000Z,Closed with non-monetary relief,Yes,8434350.0
3,2024-02-28 03:47:32+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PR,00976,NaN,Web,2024-02-28T03:53:46.000Z,Closed with explanation,Yes,8434243.0
4,2024-04-13 04:08:31+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",PR,00976,NaN,Web,2024-04-13T04:14:18.000Z,Closed with non-monetary relief,Yes,8758513.0

In [19]:
df_date["Date received"].hasnans

False

# solution

In [20]:
import pandas as pd


def convert_column_to_datetime(
    df: pd.DataFrame,
    column: str,
) -> None:
    """Convert mixed ISO 8601 strings to UTC datetimes in place.

    Date-only values are interpreted as midnight UTC.
    Invalid non-null values raise ValueError.
    """
    df[column] = pd.to_datetime(
        df[column],
        format="mixed",
        errors="raise",
        utc=True,
    )

    return df

# Product

In [21]:
df_product = df.copy()

In [22]:
len(df_product["Product"].unique())

24

In [23]:
df_product["Product"].unique()

<ArrowStringArray>
[                                                             'Debt collection',
                          'Credit reporting or other personal consumer reports',
                                                                     'Mortgage',
                                                  'Checking or savings account',
                                                                 'Student loan',
                      'Payday loan, title loan, personal loan, or advance loan',
                                                                  'Credit card',
                                                        'Vehicle loan or lease',
                                                    'Debt or credit management',
                           'Money transfer, virtual currency, or money service',
                                                                 'Prepaid card',
                                                                            nan,
                                                                        'Other',
 'Credit reporting, credit repair services, or other personal consumer reports',
                                                  'Credit card or prepaid card',
                                                                'Consumer Loan',
                                                      'Bank account or service',
                                                'Non-financial product/service',
                                                             'Credit reporting',
                                    'Payday loan, title loan, or personal loan',
                                                                  'Payday loan',
                                                      'Other financial service',
                                                              'Money transfers',
                                                             'Virtual currency']
Length: 24, dtype: str

## Available Values

* `Debt collection`
* `Credit reporting or other personal consumer reports`
* `Mortgage`
* `Checking or savings account`
* `Student loan`
* `Payday loan, title loan, personal loan, or advance loan`
* `Credit card`
* `Vehicle loan or lease`
* `Debt or credit management`
* `Money transfer, virtual currency, or money service`
* `Prepaid card`
* `NaN` *(missing value)*
* `Other`
* `Credit reporting, credit repair services, or other personal consumer reports`
* `Credit card or prepaid card`
* `Consumer Loan`
* `Bank account or service`
* `Non-financial product/service`
* `Credit reporting`
* `Payday loan, title loan, or personal loan`
* `Payday loan`
* `Other financial service`
* `Money transfers`
* `Virtual currency`

# solution

we gotta group some of these

# Sub Product

In [24]:
df_subproduct = df.copy()

In [25]:
df_subproduct["Sub-product"].unique()

<ArrowStringArray>
[                                'Credit card debt',
                                 'Credit reporting',
                                     'FHA mortgage',
                                 'Checking account',
                                    'I do not know',
                                       'Other debt',
                                        'Auto debt',
                   'Federal student loan servicing',
                       'Conventional home mortgage',
                          'Personal line of credit',
       'General-purpose credit card or charge card',
                                      'Payday loan',
                                'Store credit card',
                                       'Title loan',
                                 'Payday loan debt',
                          'Telecommunications debt',
                   'Other personal consumer report',
                                      'Rental debt',
                                             'Loan',
                                     'Medical debt',
                                  'Debt settlement',
                         'Mobile or digital wallet',
                                            'Lease',
                                        'Gift card',
                                 'Virtual currency',
                 'Other banking product or service',
                     'Domestic (US) money transfer',
                     'General-purpose prepaid card',
                           'Credit repair services',
                                  'Savings account',
                                      'VA mortgage',
       'Home equity loan or line of credit (HELOC)',
                                 'Installment loan',
                     'International money transfer',
                  'Other advances of future income',
                                    'Mortgage debt',
                           'Manufactured home loan',
                             'Private student loan',
                      'CD (Certificate of Deposit)',
                        'Private student loan debt',
                           'Other type of mortgage',
                                    'USDA mortgage',
                        'Federal student loan debt',
                                                nan,
                          'Government benefit card',
                        'Foreign currency exchange',
                                 'Reverse mortgage',
 'Money order, traveler's check or cashier's check',
                            'Check cashing service',
                                     'Payroll card',
   'Mortgage modification or foreclosure avoidance',
                               'Earned wage access',
                                         'bank fee',
                         'Student loan debt relief',
                                        'Pawn loan',
                                   'Other mortgage',
                                      'Credit card',
                             'Student prepaid card',
            'Tax refund anticipation loan or check',
            'Other (i.e. phone, health club, etc.)',
              'Traveler's check or cashier's check',
                        'Refund anticipation check',
                                      'Money order',
           'Conventional adjustable mortgage (ARM)',
                      '(CD) Certificate of deposit',
                             'Federal student loan',
                            'Gift or merchant card',
                                          'Medical',
                                         'Mortgage',
                       'Other bank product/service',
                         'Non-federal student loan',
                                             'Auto',
                                    'Vehicle lease',
                                     'Vehicle loan',
                      'Conventional fixed mortgage',
                                    'Check cashing',
               'Home equity loan or line of credit',
                                  'Second mortgage',
                             'General purpose card',
                  'Government benefit payment card',
                       'Other special purpose card',
                                    'Mobile wallet',
                                    'Credit repair',
                      'Traveler’s/Cashier’s checks',
           'Electronic Benefit Transfer / EBT card',
                                  'ID prepaid card',
               'Cashing a check without an account',
                                     'Transit card']
Length: 88, dtype: str

In [26]:
len(df_subproduct["Sub-product"].unique())

88

# solution

group them

In [27]:
alias_map = {
    "CD (Certificate of Deposit)": "Certificate of deposit (CD)",
    "(CD) Certificate of deposit": "Certificate of deposit (CD)",

    "Other banking product or service": "Other banking product or service",
    "Other bank product/service": "Other banking product or service",

    "Mobile or digital wallet": "Mobile or digital wallet",
    "Mobile wallet": "Mobile or digital wallet",

    "Credit repair services": "Credit repair services",
    "Credit repair": "Credit repair services",

    "Home equity loan or line of credit (HELOC)": "HELOC",
    "Home equity loan or line of credit": "HELOC",

    "Other type of mortgage": "Other mortgage",
    "Other mortgage": "Other mortgage",

    "General-purpose prepaid card": "General-purpose prepaid card",
    "General purpose card": "General-purpose prepaid card",

    "Gift card": "Gift or merchant card",
    "Gift or merchant card": "Gift or merchant card",

    "Government benefit card": "Government benefit card",
    "Government benefit payment card": "Government benefit card",

    "Traveler's check or cashier's check": "Traveler's or cashier's checks",
    "Traveler’s/Cashier’s checks": "Traveler's or cashier's checks",

    "Check cashing service": "Check cashing",
    "Check cashing": "Check cashing",
    "Cashing a check without an account": "Check cashing",

    "Tax refund anticipation loan or check":
        "Refund anticipation loan or check",
    "Refund anticipation check":
        "Refund anticipation loan or check",

    "Medical": "Medical debt",
    "Medical debt": "Medical debt",
}

# Issue

In [28]:
df_issue = df.copy()

In [29]:
df_issue["Issue"].unique()

<ArrowStringArray>
[            'Took or threatened to take negative or legal action',
                            'Incorrect information on your report',
     'Applying for a mortgage or refinancing an existing mortgage',
                                             'Managing an account',
                              'False statements or representation',
                               'Attempts to collect debt not owed',
                                 'Written notification about debt',
                            'Dealing with your lender or servicer',
 'Problem with a company's investigation into an existing problem',
                                     'Improper use of your report',
 ...
                              'Charged bank acct wrong day or amt',
                                                    'Cash advance',
                             'Lender damaged or destroyed vehicle',
                                           'Unexpected/Other fees',
                                        'Lender sold the property',
                                            'Balance transfer fee',
                                                    'Adding money',
                           'Incorrect/missing disclosures or info',
                           'Advertising, marketing or disclosures',
                            'Lender damaged or destroyed property']
Length: 181, dtype: str

In [30]:
for issue in df_issue["Issue"].unique():
    print(issue)

Took or threatened to take negative or legal action
Incorrect information on your report
Applying for a mortgage or refinancing an existing mortgage
Managing an account
False statements or representation
Attempts to collect debt not owed
Written notification about debt
Dealing with your lender or servicer
Problem with a company's investigation into an existing problem
Improper use of your report
Struggling to repay your loan
Struggling to pay mortgage
Problem with the payoff process at the end of the loan
Trouble during payment process
Problem with a purchase shown on your statement
Problem when making payments
Vehicle was repossessed or sold the vehicle
Advertising and marketing, including promotional offers
Can't contact lender or servicer
Threatened to contact someone or share information improperly
Getting a loan or lease
Didn't provide services promised
Problem with additional add-on products or services
Unauthorized transactions or other transaction problem
Electronic communications
Communication tactics
Trouble using the card
Charged fees or interest you didn't expect
Closing on a mortgage
Fraud or scam
Problem with a lender or other company charging your account
Problem caused by your funds being low
Closing your account
Money was not available when promised
Problems at the end of the loan or lease
Problem with a purchase or transfer
Unable to get your credit report or credit score
Trouble using your card
Other transaction problem
Managing the loan or lease
Problem with fraud alerts or security freezes
Other features, terms, or problems
Identity theft protection or other monitoring services
Wrong amount charged or received
Repossession
Credit monitoring or identity theft protection services
Fees or interest
Getting a credit card
Confusing or missing disclosures
Opening an account
Closing an account
Problem getting a card or closing an account
Problem with a company's investigation into an existing issue
Confusing or misleading advertising or marketing
Getting the loan
Struggling to pay your loan
Managing, opening, or closing your mobile wallet account
Unauthorized withdrawals or charges
Problem with customer service
nan
Getting a line of credit
Struggling to pay your bill
Lost or stolen money order
Charged upfront or unexpected fees
Can't stop withdrawals from your bank account
Unexpected or other fees
Trouble accessing funds in your mobile or digital wallet
Other service problem
Incorrect exchange rate
Problems receiving the advance
Unexpected fees
Getting a loan
Credit limit changed
General
Received a loan you didn't apply for
Issue with income share agreement
Issue where my lender is my school
Overdraft, savings, or rewards features
Issues with repayment
Problem adding money
Money was taken from your bank account on the wrong day or for the wrong amount
Problem with credit report or credit score
Loan payment wasn't credited to your account
Was approved for a loan, but didn't receive the money
Loan modification,collection,foreclosure
Disclosure verification of debt
Problem with a credit reporting company's investigation into an existing problem
Was approved for a loan, but didn't receive money
Vehicle was damaged or destroyed the vehicle
Advertising
Problem with overdraft
Problem with cash advance
Property was damaged or destroyed property
Problems when you are unable to pay
Account opening, closing, or management
Cont'd attempts collect debt not owed
Lost or stolen refund
General issues
Incorrect information on credit report
Deposits and withdrawals
Lost or stolen check
Excessive fees
Property was sold
Problem with an overdraft
Credit reporting
Application, originator, mortgage broker
Loan servicing, payments, escrow account
Dealing with my lender or servicer
Taking/threatening an illegal action
Unauthorized transactions/trans. issues
Other
Billing disputes
Problems caused by my funds being low
Credit decision / Underwriting
Improper use of my credit report
Unable to get credit report/credit score
Can't contact lender
Credit reporting company's investigation
Improper contact or sharing of info
Shopping for a loan or lease
Making/receiving payments, sending money
Using a debit or ATM card
Overlimit fee
Payoff process
Transaction issue
Credit determination
Late fee
APR or interest rate
Can't repay my loan
Credit line increase/decrease
Credit card protection / Debt protection
Applied for loan/did not receive money
Other fee
Collection practices
Settlement process and costs
Billing statement
Closing/Cancelling account
Sale of account
Delinquent account
Customer service / Customer relations
Rewards
Arbitration
Charged fees or interest I didn't expect
Collection debt dispute
Repaying your loan
Cash advance fee
Identity theft / Fraud / Embezzlement
Forbearance / Workout plans
Application processing delay
Unsolicited issuance of credit card
Other transaction issues
Taking out the loan or lease
Bankruptcy
Advertising and marketing
Account terms and changes
Managing the line of credit
Convenience checks
Can't stop charges to bank account
Payment to acct not credited
Balance transfer
Customer service/Customer relations
Managing, opening, or closing account
Credit monitoring or identity protection
Lender repossessed or sold the vehicle
Other service issues
Received a loan I didn't apply for
Disclosures
Privacy
Overdraft, savings or rewards features
Shopping for a line of credit
Fees
Charged bank acct wrong day or amt
Cash advance
Lender damaged or destroyed vehicle
Unexpected/Other fees
Lender sold the property
Balance transfer fee
Adding money
Incorrect/missing disclosures or info
Advertising, marketing or disclosures
Lender damaged or destroyed property

In [31]:
len(df_issue["Issue"].unique())

181

# solution

group these under relevance

In [32]:
import numpy as np
import pandas as pd

issue_group_map = {
    # Debt collection
    "Took or threatened to take negative or legal action": "Debt collection",
    "False statements or representation": "Debt collection",
    "Attempts to collect debt not owed": "Debt collection",
    "Written notification about debt": "Debt collection",
    "Threatened to contact someone or share information improperly": "Debt collection",
    "Electronic communications": "Debt collection",
    "Communication tactics": "Debt collection",
    "Disclosure verification of debt": "Debt collection",
    "Cont'd attempts collect debt not owed": "Debt collection",
    "Taking/threatening an illegal action": "Debt collection",
    "Improper contact or sharing of info": "Debt collection",
    "Collection practices": "Debt collection",
    "Collection debt dispute": "Debt collection",
    # Credit reporting, monitoring, or identity protection
    "Incorrect information on your report": "Credit reporting, monitoring, or identity protection",
    "Improper use of your report": "Credit reporting, monitoring, or identity protection",
    "Unable to get your credit report or credit score": "Credit reporting, monitoring, or identity protection",
    "Problem with fraud alerts or security freezes": "Credit reporting, monitoring, or identity protection",
    "Identity theft protection or other monitoring services": "Credit reporting, monitoring, or identity protection",
    "Credit monitoring or identity theft protection services": "Credit reporting, monitoring, or identity protection",
    "Problem with credit report or credit score": "Credit reporting, monitoring, or identity protection",
    "Problem with a credit reporting company's investigation into an existing problem": "Credit reporting, monitoring, or identity protection",
    "Incorrect information on credit report": "Credit reporting, monitoring, or identity protection",
    "Credit reporting": "Credit reporting, monitoring, or identity protection",
    "Improper use of my credit report": "Credit reporting, monitoring, or identity protection",
    "Unable to get credit report/credit score": "Credit reporting, monitoring, or identity protection",
    "Credit reporting company's investigation": "Credit reporting, monitoring, or identity protection",
    "Credit monitoring or identity protection": "Credit reporting, monitoring, or identity protection",
    # Mortgage application, underwriting, or closing
    "Applying for a mortgage or refinancing an existing mortgage": "Mortgage application, underwriting, or closing",
    "Closing on a mortgage": "Mortgage application, underwriting, or closing",
    "Application, originator, mortgage broker": "Mortgage application, underwriting, or closing",
    "Credit decision / Underwriting": "Mortgage application, underwriting, or closing",
    "Settlement process and costs": "Mortgage application, underwriting, or closing",
    # Mortgage servicing, payment, or foreclosure
    "Dealing with your lender or servicer": "Mortgage servicing, payment, or foreclosure",
    "Struggling to pay mortgage": "Mortgage servicing, payment, or foreclosure",
    "Can't contact lender or servicer": "Mortgage servicing, payment, or foreclosure",
    "Loan modification,collection,foreclosure": "Mortgage servicing, payment, or foreclosure",
    "Loan servicing, payments, escrow account": "Mortgage servicing, payment, or foreclosure",
    "Dealing with my lender or servicer": "Mortgage servicing, payment, or foreclosure",
    "Can't contact lender": "Mortgage servicing, payment, or foreclosure",
    # Account opening, closing, or management
    "Managing an account": "Account opening, closing, or management",
    "Closing your account": "Account opening, closing, or management",
    "Opening an account": "Account opening, closing, or management",
    "Closing an account": "Account opening, closing, or management",
    "Account opening, closing, or management": "Account opening, closing, or management",
    "Closing/Cancelling account": "Account opening, closing, or management",
    "Managing, opening, or closing account": "Account opening, closing, or management",
    # Loan or lease application and funding
    "Getting a loan or lease": "Loan or lease application and funding",
    "Getting the loan": "Loan or lease application and funding",
    "Getting a line of credit": "Loan or lease application and funding",
    "Problems receiving the advance": "Loan or lease application and funding",
    "Getting a loan": "Loan or lease application and funding",
    "Was approved for a loan, but didn't receive the money": "Loan or lease application and funding",
    "Was approved for a loan, but didn't receive money": "Loan or lease application and funding",
    "Shopping for a loan or lease": "Loan or lease application and funding",
    "Applied for loan/did not receive money": "Loan or lease application and funding",
    "Taking out the loan or lease": "Loan or lease application and funding",
    "Shopping for a line of credit": "Loan or lease application and funding",
    # Loan or lease servicing, repayment, or payoff
    "Problem with the payoff process at the end of the loan": "Loan or lease servicing, repayment, or payoff",
    "Trouble during payment process": "Loan or lease servicing, repayment, or payoff",
    "Problem when making payments": "Loan or lease servicing, repayment, or payoff",
    "Problems at the end of the loan or lease": "Loan or lease servicing, repayment, or payoff",
    "Managing the loan or lease": "Loan or lease servicing, repayment, or payoff",
    "Issues with repayment": "Loan or lease servicing, repayment, or payoff",
    "Loan payment wasn't credited to your account": "Loan or lease servicing, repayment, or payoff",
    "Payoff process": "Loan or lease servicing, repayment, or payoff",
    "Payment to acct not credited": "Loan or lease servicing, repayment, or payoff",
    "Repaying your loan": "Loan or lease servicing, repayment, or payoff",
    "Managing the line of credit": "Loan or lease servicing, repayment, or payoff",
    # Financial hardship, delinquency, or workout
    "Struggling to repay your loan": "Financial hardship, delinquency, or workout",
    "Struggling to pay your loan": "Financial hardship, delinquency, or workout",
    "Struggling to pay your bill": "Financial hardship, delinquency, or workout",
    "Problems when you are unable to pay": "Financial hardship, delinquency, or workout",
    "Can't repay my loan": "Financial hardship, delinquency, or workout",
    "Delinquent account": "Financial hardship, delinquency, or workout",
    "Forbearance / Workout plans": "Financial hardship, delinquency, or workout",
    "Bankruptcy": "Financial hardship, delinquency, or workout",
    # Repossession, sale, or property damage
    "Vehicle was repossessed or sold the vehicle": "Repossession, sale, or property damage",
    "Repossession": "Repossession, sale, or property damage",
    "Vehicle was damaged or destroyed the vehicle": "Repossession, sale, or property damage",
    "Property was damaged or destroyed property": "Repossession, sale, or property damage",
    "Property was sold": "Repossession, sale, or property damage",
    "Lender repossessed or sold the vehicle": "Repossession, sale, or property damage",
    "Lender damaged or destroyed vehicle": "Repossession, sale, or property damage",
    "Lender sold the property": "Repossession, sale, or property damage",
    "Lender damaged or destroyed property": "Repossession, sale, or property damage",
    # Card application, access, or account management
    "Trouble using the card": "Card application, access, or account management",
    "Trouble using your card": "Card application, access, or account management",
    "Getting a credit card": "Card application, access, or account management",
    "Problem getting a card or closing an account": "Card application, access, or account management",
    "Credit limit changed": "Card application, access, or account management",
    "Using a debit or ATM card": "Card application, access, or account management",
    "Credit determination": "Card application, access, or account management",
    "Credit line increase/decrease": "Card application, access, or account management",
    "Application processing delay": "Card application, access, or account management",
    "Unsolicited issuance of credit card": "Card application, access, or account management",
    # Billing, statements, or payment posting
    "Problem with a purchase shown on your statement": "Billing, statements, or payment posting",
    "Billing disputes": "Billing, statements, or payment posting",
    "Billing statement": "Billing, statements, or payment posting",
    # Fees, interest, or exchange rates
    "Charged fees or interest you didn't expect": "Fees, interest, or exchange rates",
    "Fees or interest": "Fees, interest, or exchange rates",
    "Charged upfront or unexpected fees": "Fees, interest, or exchange rates",
    "Unexpected or other fees": "Fees, interest, or exchange rates",
    "Incorrect exchange rate": "Fees, interest, or exchange rates",
    "Unexpected fees": "Fees, interest, or exchange rates",
    "Excessive fees": "Fees, interest, or exchange rates",
    "Overlimit fee": "Fees, interest, or exchange rates",
    "Late fee": "Fees, interest, or exchange rates",
    "APR or interest rate": "Fees, interest, or exchange rates",
    "Other fee": "Fees, interest, or exchange rates",
    "Charged fees or interest I didn't expect": "Fees, interest, or exchange rates",
    "Cash advance fee": "Fees, interest, or exchange rates",
    "Fees": "Fees, interest, or exchange rates",
    "Unexpected/Other fees": "Fees, interest, or exchange rates",
    "Balance transfer fee": "Fees, interest, or exchange rates",
    # Transactions, transfers, or payment instruments
    "Problem with a purchase or transfer": "Transactions, transfers, or payment instruments",
    "Other transaction problem": "Transactions, transfers, or payment instruments",
    "Wrong amount charged or received": "Transactions, transfers, or payment instruments",
    "Lost or stolen money order": "Transactions, transfers, or payment instruments",
    "Lost or stolen refund": "Transactions, transfers, or payment instruments",
    "Deposits and withdrawals": "Transactions, transfers, or payment instruments",
    "Lost or stolen check": "Transactions, transfers, or payment instruments",
    "Making/receiving payments, sending money": "Transactions, transfers, or payment instruments",
    "Transaction issue": "Transactions, transfers, or payment instruments",
    "Other transaction issues": "Transactions, transfers, or payment instruments",
    # Fraud, scams, or unauthorized activity
    "Unauthorized transactions or other transaction problem": "Fraud, scams, or unauthorized activity",
    "Fraud or scam": "Fraud, scams, or unauthorized activity",
    "Problem with a lender or other company charging your account": "Fraud, scams, or unauthorized activity",
    "Unauthorized withdrawals or charges": "Fraud, scams, or unauthorized activity",
    "Can't stop withdrawals from your bank account": "Fraud, scams, or unauthorized activity",
    "Money was taken from your bank account on the wrong day or for the wrong amount": "Fraud, scams, or unauthorized activity",
    "Unauthorized transactions/trans. issues": "Fraud, scams, or unauthorized activity",
    "Identity theft / Fraud / Embezzlement": "Fraud, scams, or unauthorized activity",
    "Can't stop charges to bank account": "Fraud, scams, or unauthorized activity",
    "Received a loan you didn't apply for": "Fraud, scams, or unauthorized activity",
    "Received a loan I didn't apply for": "Fraud, scams, or unauthorized activity",
    "Charged bank acct wrong day or amt": "Fraud, scams, or unauthorized activity",
    # Advertising, disclosures, or promised services
    "Advertising and marketing, including promotional offers": "Advertising, disclosures, or promised services",
    "Didn't provide services promised": "Advertising, disclosures, or promised services",
    "Confusing or missing disclosures": "Advertising, disclosures, or promised services",
    "Confusing or misleading advertising or marketing": "Advertising, disclosures, or promised services",
    "Advertising": "Advertising, disclosures, or promised services",
    "Advertising and marketing": "Advertising, disclosures, or promised services",
    "Disclosures": "Advertising, disclosures, or promised services",
    "Incorrect/missing disclosures or info": "Advertising, disclosures, or promised services",
    "Advertising, marketing or disclosures": "Advertising, disclosures, or promised services",
    # Customer service or company investigation
    "Problem with a company's investigation into an existing problem": "Customer service or company investigation",
    "Problem with a company's investigation into an existing issue": "Customer service or company investigation",
    "Problem with customer service": "Customer service or company investigation",
    "Other service problem": "Customer service or company investigation",
    "Customer service / Customer relations": "Customer service or company investigation",
    "Customer service/Customer relations": "Customer service or company investigation",
    "Other service issues": "Customer service or company investigation",
    # Funds availability, deposits, or adding money
    "Money was not available when promised": "Funds availability, deposits, or adding money",
    "Problem adding money": "Funds availability, deposits, or adding money",
    "Adding money": "Funds availability, deposits, or adding money",
    # Overdraft, low funds, or related features
    "Problem caused by your funds being low": "Overdraft, low funds, or related features",
    "Overdraft, savings, or rewards features": "Overdraft, low funds, or related features",
    "Problem with overdraft": "Overdraft, low funds, or related features",
    "Problem with an overdraft": "Overdraft, low funds, or related features",
    "Problems caused by my funds being low": "Overdraft, low funds, or related features",
    "Overdraft, savings or rewards features": "Overdraft, low funds, or related features",
    # Mobile wallet account or fund access
    "Managing, opening, or closing your mobile wallet account": "Mobile wallet account or fund access",
    "Trouble accessing funds in your mobile or digital wallet": "Mobile wallet account or fund access",
    # Card features, terms, add-ons, or rewards
    "Problem with additional add-on products or services": "Card features, terms, add-ons, or rewards",
    "Other features, terms, or problems": "Card features, terms, add-ons, or rewards",
    "Problem with cash advance": "Card features, terms, add-ons, or rewards",
    "Credit card protection / Debt protection": "Card features, terms, add-ons, or rewards",
    "Sale of account": "Card features, terms, add-ons, or rewards",
    "Rewards": "Card features, terms, add-ons, or rewards",
    "Arbitration": "Card features, terms, add-ons, or rewards",
    "Account terms and changes": "Card features, terms, add-ons, or rewards",
    "Convenience checks": "Card features, terms, add-ons, or rewards",
    "Balance transfer": "Card features, terms, add-ons, or rewards",
    "Privacy": "Card features, terms, add-ons, or rewards",
    "Cash advance": "Card features, terms, add-ons, or rewards",
    # Special loan terms or arrangements
    "Issue with income share agreement": "Special loan terms or arrangements",
    "Issue where my lender is my school": "Special loan terms or arrangements",
    # General or other
    "General": "General or other",
    "General issues": "General or other",
    "Other": "General or other",
    # Unknown or missing
    "nan": "Unknown",
    np.nan: "Unknown",
    pd.NA: "Unknown",
}

# Consumer Complaint Narrative

In [33]:
df["Consumer complaint narrative"].unique()

<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          nan,
 '1. Inflated Appraisal by XXXX, XXXX Rocket Mortgage appointed XXXX, XXXX, to conduct the appraisal for my mortgage. I have substantial evidence to suggest that the property appraisal was deliberately inflated to justify a higher loan amount. This practice of inflating appraisals is a form of mortgage fraud that directly impacts the borrower by increasing the loan-to-value ratio, which can lead to financial instability and a higher likelihood of default. This is also a violation of federal law RESPA ( see Violations and Codes on last page ). \n\n2. Conflict of Interest and Deceptive Practices by Realtor My realtor, XXXX XXXX, was appointed by Rocket Mortgage and acted in the interest of Rocket Mortgage rather than in my best interest as her client. When I expressed concerns about the loan officer, XXXX XXXX, and the sudden increase in my approved loan amount from {$410000.00} to {$420000.00} ( despite higher taxes on the second property ), XXXX XXXX attempted to convince me that my concerns were unfounded and " all in my head. '' She frequently communicated with XXXX XXXX privately about my concerns and would subsequently try to persuade me to proceed with the transaction, regardless of the red flags I raised. Because of this, I felt pressured to sign closing documents because I thought I would be legally responsible for this property. \n\n3. Bait-and-Switch Tactics Rocket Mortgage engaged in bait-and-switch tactics by initially offering favorable loan terms, only to alter them during the closing process. When I questioned these changes and attempted to seek advice from other mortgage lenders, XXXX XXXX, my loan officer responded clearly with an attitude stating, " I did not know other companies were involved, '' which I interpreted as an attempt to shame me for seeking alternative advice and being knowledgeable about my options. \n\n4. Approval for a Loan Beyond My Means I was initially pre-approved for a loan amount of {$410000.00}, which was suddenly increased to {$420000.00} without a proper reassessment of my ability to repay. This practice, known as " loan churning '' or " equity stripping, '' involves approving a borrower for a higher loan amount than they can reasonably afford, often with little regard for the borrower 's debt-to-income ( DTI ) ratio. This has resulted in a mortgage payment that is nearly half of my monthly salary, which is unsustainable and places me at high risk of financial distress and default. \n\n5. Negligent and Dismissive Behavior by Rocket Mortgage Executives When I contacted Rocket Mortgage 's executive team with my concerns, I was met with dismissive and shaming behavior. Despite multiple recorded calls in which I sought clarification and education on the mortgage terms, I was essentially told that it was my fault for not understanding the complexities of the mortgage contract ( see call with XXXX XXXX who also sighed at me ). This treatment, combined with the negligent approval of a loan amount that exceeds a reasonable DTI ratio, has left me in a precarious financial situation. \n\n6. Legal Grounds for Rescission The practices described above constitute fraudulent misrepresentation, deceptive trade practices, and a violation of consumer protection laws. Under the Truth in Lending Act ( TILA ) and the Consumer Financial Protection Bureaus regulations, I am entitled to rescind the mortgage contract due to the fraudulent origination practices employed by Rocket Mortgage. There is no statute of limitations when it comes to fraudulent activity. Furthermore, the reckless disregard for my ability to repay the loan, as evidenced by the inflated loan approval and disregard for my DTI ratio, and blatant conflicts of interests strengthens the legal grounds for rescission. \n\nRequest for Amicable Resolution In light of these serious issues, I am requesting that Rocket Mortgage rescind my mortgage contract without penalty and return my down payment and closing cost, as well as the costs I incurred in lieu of this fraud. I have consulted with two consumer protection attorneys who advised that, to avoid the costs and complications of litigation, a demand letter might suffice in resolving this matter amicably, which I did XX/XX/24. However, it was scanned by Rocket Mortgage and I never received a call or email regarding my letter. I would also like to note for a contract like a mortgage to be legally binding, it usually requires the agreement of both parties, typically evidenced by their signatures. If a company or party does not sign a contract, it may not be enforceable, as my contract was only signed by XXXX XXXX. And, the mortgage application to FHA did not include XXXX XXXX XXXX on application, which was made aware of at closing that XXXX XXXX XXXX XXXX was not on deed. If a mortgage lender fails to include a spouse on an FHA loan application, resulting in the spouse not being listed on the deed, several legal and regulatory issues have been violated. Violations include : Truth in Lending Act ( TILA ), Equal Credit Opportunity Act ( ECOA ), Fair Housing Act, Breach of Contract, violations to adhere of FHA guidelines and negligence. \n\nI hope we can come to an agreement without involving ligation, Consumer Financial Protection, Attorney General, HUD or a judge. \n\nCalls to XXXX XXXX in Executive Office, XXXX XXXX, voicemail to XXXX XXXX on XX/XX/24. \n\n\n\nViolations of other codes, laws, policies, or procedures 2201 section 2201 statue of frauds, everything if you dont raise it, you waive it. All deeds of trust contain a confess judgment. \n\nSecurities is not a negotiable instrument have a maturity of more than nine months Title 15, section 78 C810 Rule 13 Mandatory Counterclaim UCC 3305 3306 16 CSR 432 3.106 D 226.23 of Tila 12 CFR CODE OF REGULATION Z RESPA 8-505 AND 8508 INVESTMENT CONTRACT NOT LOAN GOVERNED BY CONTRACT LAW',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'I deposited XXXX separate checks via chase mobile app in XX/XX/year>. The total sum of checks were aprx XXXX. Chase Bank is unable to verify checks. Chase Representative state that phone number does not match the address to the maker. These checks were issued by XXXX XXXX XXXX XXXX XXXX These checks are valid and due to me. Chase Bank refused to return checks, instead it was kept, it reflects that I was paid in maker 's account, so there is no way to reissue new checks. Chase also abruptly closed the checking account. It's been 9 months and I have not received full payment. Only the initial aprx {$400.00} dollars was released when I made the deposit. I am a landlord that decided to rent out my property to a tenant, that receive XXXX XXXX XXXX XXXX and XXXX XXXX XXXX for rental assistance. The XXXX was supposed to cover rental payments from XX/XX/year> XXXX 2024. After XXXX I received monthly checks and deposited it in XXXX XXXXXXXX XXXX. Checks are actually XXXX XXXX XXXXXXXX checks and there is no issue with verification.',

# solution

leave alone

# Company Public Response

In [34]:
df["Company public response"].unique()

<ArrowStringArray>
[                                                                                                                      nan,
                         'Company has responded to the consumer and the CFPB and chooses not to provide a public response',
                                                'Company believes it acted appropriately as authorized by contract or law',
                                                                   'Company disputes the facts presented in the complaint',
                                                      'Company believes the complaint is the result of a misunderstanding',
                                                           'Company believes complaint is the result of an isolated error',
                                   'Company believes the complaint provided an opportunity to answer consumer's questions',
                          'Company believes complaint represents an opportunity for improvement to better serve consumers',
                                                              'Company can't verify or dispute the facts in the complaint',
 'Company believes complaint caused principally by actions of third party outside the control or direction of the company',
                                                                        'Company chooses not to provide a public response',
                                                'Company believes complaint relates to a discontinued policy or procedure']
Length: 12, dtype: str

# Company

In [35]:
df["Company"].unique()

<ArrowStringArray>
[         'Protas, Spivok & Collins. LLC',
 'TRANSUNION INTERMEDIATE HOLDINGS, INC.',
    'Experian Information Solutions Inc.',
                          'EQUIFAX, INC.',
                   'Rocket Mortgage, LLC',
                   'JPMORGAN CHASE & CO.',
          'VIRTUOSO SOURCING GROUP, LLC.',
                                 'MOHELA',
                          'PNC Bank N.A.',
                  'Pending Company Match',
 ...
           'Ozark Mountain Mortgage, LLC',
                     'Beloin & Brown LLC',
          'XPRESS CREDIT MANAGEMENT, LLC',
                   'DriveNow Leasing LLC',
               'Costner Law Office, PLLC',
                   'Lender Services, Inc',
                         'PLAC Guarantee',
                             'PCMA, Inc.',
                  'Premium Security Inc.',
      'Randolph Walzer & Associates, LLC']
Length: 8032, dtype: str

In [36]:
len(df["Company"].unique())

8032

In [37]:
def find_chase(strings):
    return [s for s in strings if "chase" in s.lower()]

In [38]:
chase = find_chase(df["Company"])

In [39]:
chase_set = set(chase)

In [40]:
chase_set

{'JPMORGAN CHASE & CO.'}

In [41]:
def find_pnc(strings):
    return [ s for s in strings if "pnc" in s.lower()]

In [42]:
pnc = find_pnc(df["Company"])
pnc_set = set(pnc)
pnc_set

{'PNC Bank N.A.'}

# solution

Assume the strings are correct

# State

In [43]:
df["State"].unique()

<ArrowStringArray>
[                                  'VA',
                                   'PR',
                                   'GA',
                                   'NV',
                                   'OH',
                                   'MO',
                                   'MD',
                                   'PA',
                                   'DE',
                                   'FL',
                                   'UT',
                                   'NJ',
                                   'WA',
                                   'TN',
                                   'TX',
                                   'CA',
                                   'NC',
                                   'IL',
                                   'CT',
                                   'IN',
                                   'CO',
                                   'NY',
                                   'MN',
                                   'HI',
                                   'AZ',
                                   'SD',
                                   'ND',
                                   'SC',
                                   'AL',
                                   'OK',
                                   'OR',
                                   'IA',
                                   'WI',
                                   'MI',
                                   'MS',
                                   'NE',
                                   'MT',
                                   'MA',
                                   'LA',
                                   'KY',
                                   'AR',
                                   'NH',
                                    nan,
                                   'RI',
                                   'NM',
                                   'KS',
                                   'DC',
 'UNITED STATES MINOR OUTLYING ISLANDS',
                                   'ID',
                                   'VT',
                                   'WV',
                                   'ME',
                                   'AK',
                                   'AP',
                                   'VI',
                                   'WY',
                                   'AE',
                                   'AA',
                                   'GU',
                                   'PW',
                                   'AS',
                                   'MP',
                                   'FM',
                                   'MH']
Length: 64, dtype: str

In [44]:
df["State"].hasnans

True

# solution

Leave Alone, but know that a record could not have missing value for state


Those are USPS state abbreviations

# ZIP code

In [45]:
df["ZIP code"].hasnans

True

In [46]:
# df[df["ZIP code"].isna() & ~df["State"].isna()]

In [47]:
from typing import Any
import pandas as pd


def convert_str_int(column: pd.Series) -> pd.Series:
    def convert_value(item: tuple[Any, Any]) -> int:
        index, value = item

        try:
            return int(value)
        except (TypeError, ValueError) as exc:
            raise ValueError(
                f"Cannot convert value {value!r} to int at index {index!r}"
            ) from exc

    converted = map(convert_value, column.items())

    return pd.Series(converted, index=column.index, name=column.name, dtype="int64")

In [48]:
df_zip = df.copy()

In [49]:
# df_zip["ZIP code"] = convert_str_int(df_zip["ZIP code"])

# Cannot convert value '891XX' to int at index 14

# solution
There are null zip values, and some have state with no zips as well, convert the ones present into integer

There are also some values with format 891xxx , incomplete but usable in certain situations, keep it as is?

for now keep it

# Tags

In [50]:
# len(df["Tags"].unique())

# solution
ignore for now, took too long to run

# Submitted via

In [51]:
df["Submitted via"].unique()

<ArrowStringArray>
['Web', 'Referral', 'Phone', 'Postal mail', nan, 'Email', 'Fax']
Length: 7, dtype: str

# solution

leave as is, know it is properly grouped

# Date sent to company

In [52]:
df["Date sent to company"].head()

0    2023-03-24T05:01:41.000Z
1    2024-03-04T18:31:15.000Z
2    2024-02-28T03:54:30.000Z
3    2024-02-28T03:53:46.000Z
4    2024-04-13T04:14:18.000Z
Name: Date sent to company, dtype: str

In [5]:
df_date_sent = df.copy()

In [3]:
import pandas as pd


def convert_column_to_datetime(
    df: pd.DataFrame,
    column: str,
) -> None:
    """Convert mixed ISO 8601 strings to UTC datetimes in place.

    Date-only values are interpreted as midnight UTC.
    Invalid non-null values raise ValueError.
    """
    df[column] = pd.to_datetime(
        df[column],
        format="mixed",
        errors="raise",
        utc=True,
    )

    return df

In [6]:
df_date_sent = convert_column_to_datetime(df_date_sent, "Date sent to company")

In [7]:
df_date_sent.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2023-03-24T04:36:20.000Z,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Collected or attempted to collect exempt funds,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22406,Servicemember,Web,2023-03-24 05:01:41+00:00,Closed with explanation,No,6747064.0
1,2024-02-26T22:23:15.000Z,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Sued you without properly notifying you of law...,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22042,NaN,Web,2024-03-04 18:31:15+00:00,Closed with explanation,No,8424458.0
2,2024-02-28T03:49:51.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PR,00976,NaN,Web,2024-02-28 03:54:30+00:00,Closed with non-monetary relief,Yes,8434350.0
3,2024-02-28T03:47:32.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PR,00976,NaN,Web,2024-02-28 03:53:46+00:00,Closed with explanation,Yes,8434243.0
4,2024-04-13T04:08:31.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",PR,00976,NaN,Web,2024-04-13 04:14:18+00:00,Closed with non-monetary relief,Yes,8758513.0

In [8]:
df_date_sent.info()

<class 'pandas.DataFrame'>
RangeIndex: 16505480 entries, 0 to 16505479
Data columns (total 16 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 str
 1   Product                       str
 2   Sub-product                   str
 3   Issue                         str
 4   Sub-issue                     str
 5   Consumer complaint narrative  str
 6   Company public response       str
 7   Company                       str
 8   State                         str
 9   ZIP code                      str
 10  Tags                          str
 11  Submitted via                 str
 12  Date sent to company          datetime64[us, UTC]
 13  Company response to consumer  str
 14  Timely response?              str
 15  Complaint ID                  float64
dtypes: datetime64[us, UTC](1), float64(1), str(14)
memory usage: 9.7 GB

# solution

In [14]:
import pandas as pd


def convert_column_to_datetime(
    df: pd.DataFrame,
    column: str,
) -> pd.DataFrame:
    """Convert mixed ISO 8601 strings to UTC datetimes in place.

    Date-only values are interpreted as midnight UTC.
    Invalid non-null values raise ValueError.
    """
    df[column] = pd.to_datetime(
        df[column],
        format="mixed",
        errors="raise",
        utc=True,
    )

    return df

# Company response to consumer

In [10]:
df["Company response to consumer"].unique()

<ArrowStringArray>
[        'Closed with explanation', 'Closed with non-monetary relief',
                               nan,               'Untimely response',
     'Closed with monetary relief',                     'In progress',
                          'Closed',           'Closed without relief',
              'Closed with relief']
Length: 9, dtype: str

# solution

In [ ]:
# group 

status_mapping = {
    # Closed — relief provided
    "Closed with monetary relief": "Closed - With relief",
    "Closed with non-monetary relief": "Closed - With relief",
    "Closed with relief": "Closed - With relief",

    # Closed — no relief provided
    "Closed without relief": "Closed - Without relief",
    "Closed with explanation": "Closed - Without relief",

    # Closed — outcome unspecified
    "Closed": "Closed - Unspecified",

    # Not closed
    "In progress": "In progress",
    "Untimely response": "Untimely response",
}

# Timely response

In [13]:
df["Timely response?"].unique()

<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [15]:
def boolify(df, col):
    mapping = {"Yes": True, "No": False}

    invalid = df.loc[
        df[col].notna() & ~df[col].isin(mapping),
        col
    ].unique()

    if len(invalid) > 0:
        raise ValueError(f"Unexpected values in {col!r}: {invalid.tolist()}")

    df[col] = df[col].map(mapping).astype("boolean")
    return df

In [16]:
df_timely = df.copy()

In [17]:
df_timely = boolify(df_timely, "Timely response?")

In [18]:
df_timely.info()

<class 'pandas.DataFrame'>
RangeIndex: 16505480 entries, 0 to 16505479
Data columns (total 16 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 str
 1   Product                       str
 2   Sub-product                   str
 3   Issue                         str
 4   Sub-issue                     str
 5   Consumer complaint narrative  str
 6   Company public response       str
 7   Company                       str
 8   State                         str
 9   ZIP code                      str
 10  Tags                          str
 11  Submitted via                 str
 12  Date sent to company          str
 13  Company response to consumer  str
 14  Timely response?              boolean
 15  Complaint ID                  float64
dtypes: boolean(1), float64(1), str(14)
memory usage: 9.8 GB

# Complaint ID

In [20]:
def strict_float_to_int(df, col):
    df_copy = df.copy()
    df_copy[col] = df_copy[col].astype("Int64")
    return df_copy

In [19]:
df_complaint_id = df.copy()

In [22]:
df_complaint_id = strict_float_to_int(df_complaint_id, "Complaint ID")

In [23]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2023-03-24T04:36:20.000Z,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Collected or attempted to collect exempt funds,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22406,Servicemember,Web,2023-03-24T05:01:41.000Z,Closed with explanation,No,6747064.0
1,2024-02-26T22:23:15.000Z,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Sued you without properly notifying you of law...,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22042,NaN,Web,2024-03-04T18:31:15.000Z,Closed with explanation,No,8424458.0
2,2024-02-28T03:49:51.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PR,00976,NaN,Web,2024-02-28T03:54:30.000Z,Closed with non-monetary relief,Yes,8434350.0
3,2024-02-28T03:47:32.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PR,00976,NaN,Web,2024-02-28T03:53:46.000Z,Closed with explanation,Yes,8434243.0
4,2024-04-13T04:08:31.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",PR,00976,NaN,Web,2024-04-13T04:14:18.000Z,Closed with non-monetary relief,Yes,8758513.0

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16505480 entries, 0 to 16505479
Data columns (total 16 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 str
 1   Product                       str
 2   Sub-product                   str
 3   Issue                         str
 4   Sub-issue                     str
 5   Consumer complaint narrative  str
 6   Company public response       str
 7   Company                       str
 8   State                         str
 9   ZIP code                      str
 10  Tags                          str
 11  Submitted via                 str
 12  Date sent to company          str
 13  Company response to consumer  str
 14  Timely response?              str
 15  Complaint ID                  float64
dtypes: float64(1), str(15)
memory usage: 9.9 GB

# solution

In [25]:
def strict_float_to_int(df, col):
    df_copy = df.copy()
    df_copy[col] = df_copy[col].astype("Int64")
    return df_copy