In [35]:
import pandas as pd

In [37]:
df = pd.read_csv("complaints.csv/complaints.csv")

/var/folders/zb/04xtvn511zjb4fk9g9rhthjw0000gn/T/ipykernel_24094/3241862011.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("complaints.csv/complaints.csv")

In [38]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2023-03-24T04:36:20.000Z,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Collected or attempted to collect exempt funds,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22406,Servicemember,Web,2023-03-24T05:01:41.000Z,Closed with explanation,No,6747064.0
1,2024-02-26T22:23:15.000Z,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Sued you without properly notifying you of law...,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22042,NaN,Web,2024-03-04T18:31:15.000Z,Closed with explanation,No,8424458.0
2,2024-02-28T03:49:51.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PR,00976,NaN,Web,2024-02-28T03:54:30.000Z,Closed with non-monetary relief,Yes,8434350.0
3,2024-02-28T03:47:32.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PR,00976,NaN,Web,2024-02-28T03:53:46.000Z,Closed with explanation,Yes,8434243.0
4,2024-04-13T04:08:31.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",PR,00976,NaN,Web,2024-04-13T04:14:18.000Z,Closed with non-monetary relief,Yes,8758513.0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16505480 entries, 0 to 16505479
Data columns (total 16 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 object
 1   Product                       object
 2   Sub-product                   object
 3   Issue                         object
 4   Sub-issue                     object
 5   Consumer complaint narrative  object
 6   Company public response       object
 7   Company                       object
 8   State                         object
 9   ZIP code                      object
 10  Tags                          object
 11  Submitted via                 object
 12  Date sent to company          object
 13  Company response to consumer  object
 14  Timely response?              object
 15  Complaint ID                  float64
dtypes: float64(1), object(15)
memory usage: 2.0+ GB

# Deduplicate

In [ ]:
df["Complaint ID"].is_unique

False

In [ ]:
dupes = df[df["Complaint ID"].duplicated(keep=False)].sort_values("Complaint ID")

In [ ]:
dupes

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
37,2025-06-10T18:13:45.000Z,Mortgage,Conventional home mortgage,Struggling to pay mortgage,Trying to communicate with the company to fix ...,NaN,NaN,Pending Company Match,GA,30012,NaN,Referral,NaN,NaN,Yes,NaN
39,2025-06-30T01:08:10.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",WA,NaN,NaN,Web,2025-06-30T01:11:46.000Z,NaN,Yes,NaN
46,2025-08-21T06:04:40.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",WA,NaN,NaN,Web,2025-08-21T08:00:47.000Z,NaN,Yes,NaN
49,2025-10-01T06:35:14.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",WA,NaN,NaN,Web,2025-10-01T08:00:49.000Z,NaN,Yes,NaN
53,2025-10-08T00:15:19.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",WA,NaN,NaN,Web,2025-10-08T00:18:19.000Z,NaN,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176256,2026-07-03T09:08:04.000Z,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,NaN,NaN,Pending Company Match,NaN,NaN,NaN,Web,NaN,NaN,Yes,NaN
176257,2026-07-03T09:06:15.000Z,Debt collection,I do not know,Written notification about debt,Didn't receive enough information to verify debt,NaN,NaN,Pending Company Match,TX,78253,NaN,Web,NaN,NaN,Yes,NaN
176258,2026-07-03T09:04:29.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Account information incorrect,NaN,NaN,Pending Company Match,TX,77477,NaN,Web,NaN,NaN,Yes,NaN
176261,2026-07-03T09:08:12.000Z,Checking or savings account,NaN,NaN,NaN,NaN,NaN,Pending Company Match,OH,45424,NaN,Referral,NaN,NaN,Yes,NaN
176263,2026-07-03T09:04:38.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,Pending Company Match,NaN,NaN,NaN,Web,NaN,NaN,Yes,NaN

In [ ]:
dupes["Complaint ID"].unique()

array([nan])

In [ ]:
dupes["Company"].unique()

array(['Pending Company Match', 'TRANSUNION INTERMEDIATE HOLDINGS, INC.',
       'Westlake Services, LLC', 'ENCORE CAPITAL GROUP INC.',
       'Resurgent Capital Services L.P.', 'I.C. System, Inc.',
       'CAPITAL ONE FINANCIAL CORPORATION', 'EQUIFAX, INC.',
       'NAVY FEDERAL CREDIT UNION', 'Experian Information Solutions Inc.',
       'SLM CORPORATION', 'BANK OF NEW YORK MELLON CORPORATION, THE',
       'JPMORGAN CHASE & CO.', 'Nelnet, Inc.', 'Debt Recovery Pro ,LLC',
       'CCS Financial Services, Inc.', 'OPT-OUT SERVICES, LLC',
       'LEXISNEXIS', 'Bread Financial Holdings, Inc.', 'CarMax, Inc.',
       'CBC Companies, Inc.', 'CREDIT ACCEPTANCE CORPORATION',
       'Fidelity National Information Services, Inc. (FNIS)',
       'MoneyLion Inc.', 'Affirm Holdings, Inc', 'Klarna AB',
       'ID Analytics, Inc.', 'Americas Car-Mart, Inc.',
       'BANK OF AMERICA, NATIONAL ASSOCIATION', 'Self Financial Inc.',
       'SOFI TECHNOLOGIES, INC.', 'Aqua Finance, Inc.',
       'HSBC NORTH AMERICA HOLDINGS INC.', 'Freedom Mortgage Company',
       'BARCLAYS BANK DELAWARE', 'CITIZENS FINANCIAL GROUP, INC.',
       'TD BANK US HOLDING COMPANY',
       'Diversified Adjustment Service, Inc.',
       'Global Lending Services LLC', 'Central Research Inc',
       'SOUTHSTATE BANK CORPORATION', 'PNC Bank N.A.',
       'American First Finance, Inc.', 'STATE EMPLOYEES CREDIT UNION',
       'TRUIST FINANCIAL CORPORATION', 'CORELOGIC INC', 'MOHELA',
       'REGIONS FINANCIAL CORPORATION', 'SUN LOAN COMPANY INC.',
       'Lockhart, Morris & Montgomery Inc.',
       'BMW Financial Services NA, LLC', 'Rausch Sturm LLP',
       'AMERICAN EXPRESS COMPANY',
       'Lincoln Educational Services Corporation', 'T.S. Holdings',
       'NRA Group, LLC', 'National Recovery Solutions, LLC',
       'KEYSTONE EQUIPMENT FINANCE CORP.',
       'Larry H. Miller Group of Companies',
       'General Motors Financial Company, Inc.', 'Comerica',
       'Exeter Finance, LLC.', 'Sezzle Inc.',
       'CCF Intermediate Holdings LLC', 'NCB Management Services Inc.',
       'Asset Recovery Bureau LLC', 'FIRST CAPITAL GROUP, INC.',
       'ALLY FINANCIAL INC.', 'Kahn, Dees, Donovan & Kahn, LLP',
       'Portfolio Recovery Associates, LLC',
       'OPORTUN FINANCIAL CORPORATION', 'Spring Oaks Capital, LLC',
       'Diverse Funding Associates LLC', 'CITIBANK, N.A.',
       'CL Holdings LLC', 'HUNTINGTON NATIONAL BANK, THE',
       'Alphaeon Credit, Inc.', 'V and H Portfolio',
       'UNITED SERVICES AUTOMOBILE ASSOCIATION', 'Kikoff Inc.',
       'SANTANDER HOLDINGS USA, INC.', 'BTH Management',
       'CAVALRY INVESTMENTS, LLC', 'Accounts Receivable Inc.',
       'Credit Corp Solutions Inc.', 'RFNA, LP', 'SinglePoint GI',
       'American Credit Acceptance, LLC', 'CLGF Holdco 1, LLC',
       'ONLINE Information Services, Inc.', 'Opportunity Financial, LLC',
       'PREFERRED CREDIT INC', 'National Credit Adjusters, LLC',
       'French Financial, Inc.', 'Rocket Mortgage, LLC',
       'LCS FINANCIAL SERVICES CORPORATION', 'Merchants Acceptance Corp',
       'Alliance Credit Services, Inc.', 'Cascade CISS Holdings, LLC',
       'BMO BANK NATIONAL ASSOCIATION', 'Servatus Corporation',
       'Chime Financial Inc', 'LJ Ross Associates',
       'Roadrunner Account Services, LLC', 'U.S. BANCORP',
       'AMERICA FIRST FEDERAL CREDIT UNION', 'UPGRADE, INC.',
       'FIFTH THIRD FINANCIAL CORPORATION', 'The Phoenix Recovery Group',
       'TOYOTA MOTOR CREDIT CORPORATION', 'EGL US, LLC',
       'EdFinancial Services', 'UNITED AUTO ACCEPTANCE',
       'Revolut Technologies Inc.', 'PENTAGON FEDERAL CREDIT UNION',
       'Camino Financial Inc.', 'Paypal Holdings, Inc',
       'Mid-Atlantic Portfolios, LLC', 'Kriya Capital, LLC',
       'Byrider Franchising, LLC', 'Foris DAX, Inc.',
       'Fidelity National Financial, Inc', 'Telerecovery Corporation',
       'National Credit Systems,Inc.', 'HYUNDAI CAPITAL AMERICA',
       'Populus Financial Group, Inc. (F/K/A Ace Cash Express)',
       'PROSPERITY BANCSHARES, INC.', 'Benuck & Rainey, Inc.',
       'Selene Holdings LLC', 'Avant Holding Company, Inc.',
       'ROBINHOOD MARKETS INC.', 'Works & Lentz of Tulsa, Inc.',
       'WELLS FARGO & COMPANY', 'Ocwen Financial Corporation',
       'FIRST FINANCIAL BANCORP', 'ACIMA CREDIT, LLC',
       'Maximus Federal Services, Inc.', 'Paylaterr Inc',
       'Rowland Avenue Management, Inc. A/KA Columbia Debt Recovery, LLC d/b/a Genesis',
       'TEXAS CAPITAL BANCSHARES, INC.',
       'Associated Credit Services, Inc.', 'AMERICAN HONDA FINANCE CORP',
       'Shellpoint Partners, LLC', 'Indigo Ultimate Parent, LLC',
       'SYNCHRONY FINANCIAL', 'Dave Operating, LLC',
       'Security Credit Services, LLC',
       'Sentry Recovery and Collections, Inc.',
       'Southern Management Systems Inc.', 'Adelante, Inc', 'OKX INC.',
       'Risecredit, LLC', 'Radius Global Solutions LLC',
       'Credit Karma, LLC', 'Monterey Financial Services LLC',
       '500 Down Dallas, LLC', 'Paramount GR Holdings, LLC',
       'Block, Inc.', 'Nationwide Capital Services, LLC',
       'BANK OF HAWAII CORPORATION', 'ENOVA INTERNATIONAL, INC.'],
      dtype=object)

In [ ]:
df["id_missing"] = df["Complaint ID"].isna()
df["id_missing"].mean()   # overall proportion missing

0.0007801651330346043

In [ ]:
def missingness_by_category(df, col, flag="id_missing"):
    out = df.groupby(col, observed=True)[flag].agg(["mean", "size"])
    out = out.rename(columns={"mean": "missing_rate", "size": "n"})
    return out.sort_values("missing_rate", ascending=False)

missingness_by_category(df, "Company response to consumer")
missingness_by_category(df, "Submitted via")
missingness_by_category(df, "Product")
missingness_by_category(df, "State")

       missing_rate        n
State
MS         0.001597   264262
NC         0.000961   565291
TX         0.000895  2244858
FL         0.000881  2255172
HI         0.000839    28596
...             ...      ...
MH         0.000000       33
PW         0.000000       50
AE         0.000000     2654
MP         0.000000      109
AA         0.000000      160

[63 rows x 2 columns]

Allow the complaint to exist along with the other features that are collected

# Date received

## Date utility

In [53]:
df_date = df.copy()

In [42]:
df_date["Date received"].head()

0    2023-03-24T04:36:20.000Z
1    2024-02-26T22:23:15.000Z
2    2024-02-28T03:49:51.000Z
3    2024-02-28T03:47:32.000Z
4    2024-04-13T04:08:31.000Z
Name: Date received, dtype: object

In [51]:
import pandas as pd


def convert_column_to_datetime(
    df: pd.DataFrame,
    column: str,
) -> None:
    """Convert mixed ISO 8601 strings to UTC datetimes in place.

    Date-only values are interpreted as midnight UTC.
    Invalid non-null values raise ValueError.
    """
    df[column] = pd.to_datetime(
        df[column],
        format="mixed",
        errors="raise",
        utc=True,
    )

    return df

In [54]:
df_date = convert_column_to_datetime(df_date, "Date received")

In [55]:
df_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16505480 entries, 0 to 16505479
Data columns (total 16 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 datetime64[ns, UTC]
 1   Product                       object
 2   Sub-product                   object
 3   Issue                         object
 4   Sub-issue                     object
 5   Consumer complaint narrative  object
 6   Company public response       object
 7   Company                       object
 8   State                         object
 9   ZIP code                      object
 10  Tags                          object
 11  Submitted via                 object
 12  Date sent to company          object
 13  Company response to consumer  object
 14  Timely response?              object
 15  Complaint ID                  float64
dtypes: datetime64[ns, UTC](1), float64(1), object(14)
memory usage: 2.0+ GB

In [56]:
df_date.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2023-03-24 04:36:20+00:00,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Collected or attempted to collect exempt funds,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22406,Servicemember,Web,2023-03-24T05:01:41.000Z,Closed with explanation,No,6747064.0
1,2024-02-26 22:23:15+00:00,Debt collection,Credit card debt,Took or threatened to take negative or legal a...,Sued you without properly notifying you of law...,NaN,NaN,"Protas, Spivok & Collins. LLC",VA,22042,NaN,Web,2024-03-04T18:31:15.000Z,Closed with explanation,No,8424458.0
2,2024-02-28 03:49:51+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PR,00976,NaN,Web,2024-02-28T03:54:30.000Z,Closed with non-monetary relief,Yes,8434350.0
3,2024-02-28 03:47:32+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PR,00976,NaN,Web,2024-02-28T03:53:46.000Z,Closed with explanation,Yes,8434243.0
4,2024-04-13 04:08:31+00:00,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",PR,00976,NaN,Web,2024-04-13T04:14:18.000Z,Closed with non-monetary relief,Yes,8758513.0

In [57]:
df_date["Date received"].hasnans

False

# Product

In [58]:
df_product = df.copy()

In [62]:
len(df_product["Product"].unique())

24

In [63]:
df_product["Product"].unique()

array(['Debt collection',
       'Credit reporting or other personal consumer reports', 'Mortgage',
       'Checking or savings account', 'Student loan',
       'Payday loan, title loan, personal loan, or advance loan',
       'Credit card', 'Vehicle loan or lease',
       'Debt or credit management',
       'Money transfer, virtual currency, or money service',
       'Prepaid card', nan, 'Other',
       'Credit reporting, credit repair services, or other personal consumer reports',
       'Credit card or prepaid card', 'Consumer Loan',
       'Bank account or service', 'Non-financial product/service',
       'Credit reporting', 'Payday loan, title loan, or personal loan',
       'Payday loan', 'Other financial service', 'Money transfers',
       'Virtual currency'], dtype=object)

## Available Values

* `Debt collection`
* `Credit reporting or other personal consumer reports`
* `Mortgage`
* `Checking or savings account`
* `Student loan`
* `Payday loan, title loan, personal loan, or advance loan`
* `Credit card`
* `Vehicle loan or lease`
* `Debt or credit management`
* `Money transfer, virtual currency, or money service`
* `Prepaid card`
* `NaN` *(missing value)*
* `Other`
* `Credit reporting, credit repair services, or other personal consumer reports`
* `Credit card or prepaid card`
* `Consumer Loan`
* `Bank account or service`
* `Non-financial product/service`
* `Credit reporting`
* `Payday loan, title loan, or personal loan`
* `Payday loan`
* `Other financial service`
* `Money transfers`
* `Virtual currency`

debt collection , credit reporting, mortgage , checking or savings, student loan, payday loan title loan personal loan or advance loan

# Sub Product

In [64]:
df_subproduct = df.copy()

In [67]:
df_subproduct["Sub-product"].unique()

array(['Credit card debt', 'Credit reporting', 'FHA mortgage',
       'Checking account', 'I do not know', 'Other debt', 'Auto debt',
       'Federal student loan servicing', 'Conventional home mortgage',
       'Personal line of credit',
       'General-purpose credit card or charge card', 'Payday loan',
       'Store credit card', 'Title loan', 'Payday loan debt',
       'Telecommunications debt', 'Other personal consumer report',
       'Rental debt', 'Loan', 'Medical debt', 'Debt settlement',
       'Mobile or digital wallet', 'Lease', 'Gift card',
       'Virtual currency', 'Other banking product or service',
       'Domestic (US) money transfer', 'General-purpose prepaid card',
       'Credit repair services', 'Savings account', 'VA mortgage',
       'Home equity loan or line of credit (HELOC)', 'Installment loan',
       'International money transfer', 'Other advances of future income',
       'Mortgage debt', 'Manufactured home loan', 'Private student loan',
       'CD (Certificate of Deposit)', 'Private student loan debt',
       'Other type of mortgage', 'USDA mortgage',
       'Federal student loan debt', nan, 'Government benefit card',
       'Foreign currency exchange', 'Reverse mortgage',
       "Money order, traveler's check or cashier's check",
       'Check cashing service', 'Payroll card',
       'Mortgage modification or foreclosure avoidance',
       'Earned wage access', 'bank fee', 'Student loan debt relief',
       'Pawn loan', 'Other mortgage', 'Credit card',
       'Student prepaid card', 'Tax refund anticipation loan or check',
       'Other (i.e. phone, health club, etc.)',
       "Traveler's check or cashier's check", 'Refund anticipation check',
       'Money order', 'Conventional adjustable mortgage (ARM)',
       '(CD) Certificate of deposit', 'Federal student loan',
       'Gift or merchant card', 'Medical', 'Mortgage',
       'Other bank product/service', 'Non-federal student loan', 'Auto',
       'Vehicle lease', 'Vehicle loan', 'Conventional fixed mortgage',
       'Check cashing', 'Home equity loan or line of credit',
       'Second mortgage', 'General purpose card',
       'Government benefit payment card', 'Other special purpose card',
       'Mobile wallet', 'Credit repair', 'Traveler’s/Cashier’s checks',
       'Electronic Benefit Transfer / EBT card', 'ID prepaid card',
       'Cashing a check without an account', 'Transit card'], dtype=object)

In [68]:
len(df_subproduct["Sub-product"].unique())

88

# Issue

In [69]:
df_issue = df.copy()

In [70]:
df_issue["Issue"].unique()

array(['Took or threatened to take negative or legal action',
       'Incorrect information on your report',
       'Applying for a mortgage or refinancing an existing mortgage',
       'Managing an account', 'False statements or representation',
       'Attempts to collect debt not owed',
       'Written notification about debt',
       'Dealing with your lender or servicer',
       "Problem with a company's investigation into an existing problem",
       'Improper use of your report', 'Struggling to repay your loan',
       'Struggling to pay mortgage',
       'Problem with the payoff process at the end of the loan',
       'Trouble during payment process',
       'Problem with a purchase shown on your statement',
       'Problem when making payments',
       'Vehicle was repossessed or sold the vehicle',
       'Advertising and marketing, including promotional offers',
       "Can't contact lender or servicer",
       'Threatened to contact someone or share information improperly',
       'Getting a loan or lease', "Didn't provide services promised",
       'Problem with additional add-on products or services',
       'Unauthorized transactions or other transaction problem',
       'Electronic communications', 'Communication tactics',
       'Trouble using the card',
       "Charged fees or interest you didn't expect",
       'Closing on a mortgage', 'Fraud or scam',
       'Problem with a lender or other company charging your account',
       'Problem caused by your funds being low', 'Closing your account',
       'Money was not available when promised',
       'Problems at the end of the loan or lease',
       'Problem with a purchase or transfer',
       'Unable to get your credit report or credit score',
       'Trouble using your card', 'Other transaction problem',
       'Managing the loan or lease',
       'Problem with fraud alerts or security freezes',
       'Other features, terms, or problems',
       'Identity theft protection or other monitoring services',
       'Wrong amount charged or received', 'Repossession',
       'Credit monitoring or identity theft protection services',
       'Fees or interest', 'Getting a credit card',
       'Confusing or missing disclosures', 'Opening an account',
       'Closing an account',
       'Problem getting a card or closing an account',
       "Problem with a company's investigation into an existing issue",
       'Confusing or misleading advertising or marketing',
       'Getting the loan', 'Struggling to pay your loan',
       'Managing, opening, or closing your mobile wallet account',
       'Unauthorized withdrawals or charges',
       'Problem with customer service', nan, 'Getting a line of credit',
       'Struggling to pay your bill', 'Lost or stolen money order',
       'Charged upfront or unexpected fees',
       "Can't stop withdrawals from your bank account",
       'Unexpected or other fees',
       'Trouble accessing funds in your mobile or digital wallet',
       'Other service problem', 'Incorrect exchange rate',
       'Problems receiving the advance', 'Unexpected fees',
       'Getting a loan', 'Credit limit changed', 'General',
       "Received a loan you didn't apply for",
       'Issue with income share agreement',
       'Issue where my lender is my school',
       'Overdraft, savings, or rewards features', 'Issues with repayment',
       'Problem adding money',
       'Money was taken from your bank account on the wrong day or for the wrong amount',
       'Problem with credit report or credit score',
       "Loan payment wasn't credited to your account",
       "Was approved for a loan, but didn't receive the money",
       'Loan modification,collection,foreclosure',
       'Disclosure verification of debt',
       "Problem with a credit reporting company's investigation into an existing problem",
       "Was approved for a loan, but didn't receive money",
       'Vehicle was damaged or destroyed the vehicle', 'Advertising',
       'Problem with overdraft', 'Problem with cash advance',
       'Property was damaged or destroyed property',
       'Problems when you are unable to pay',
       'Account opening, closing, or management',
       "Cont'd attempts collect debt not owed", 'Lost or stolen refund',
       'General issues', 'Incorrect information on credit report',
       'Deposits and withdrawals', 'Lost or stolen check',
       'Excessive fees', 'Property was sold', 'Problem with an overdraft',
       'Credit reporting', 'Application, originator, mortgage broker',
       'Loan servicing, payments, escrow account',
       'Dealing with my lender or servicer',
       'Taking/threatening an illegal action',
       'Unauthorized transactions/trans. issues', 'Other',
       'Billing disputes', 'Problems caused by my funds being low',
       'Credit decision / Underwriting',
       'Improper use of my credit report',
       'Unable to get credit report/credit score', "Can't contact lender",
       "Credit reporting company's investigation",
       'Improper contact or sharing of info',
       'Shopping for a loan or lease',
       'Making/receiving payments, sending money',
       'Using a debit or ATM card', 'Overlimit fee', 'Payoff process',
       'Transaction issue', 'Credit determination', 'Late fee',
       'APR or interest rate', "Can't repay my loan",
       'Credit line increase/decrease',
       'Credit card protection / Debt protection',
       'Applied for loan/did not receive money', 'Other fee',
       'Collection practices', 'Settlement process and costs',
       'Billing statement', 'Closing/Cancelling account',
       'Sale of account', 'Delinquent account',
       'Customer service / Customer relations', 'Rewards', 'Arbitration',
       "Charged fees or interest I didn't expect",
       'Collection debt dispute', 'Repaying your loan',
       'Cash advance fee', 'Identity theft / Fraud / Embezzlement',
       'Forbearance / Workout plans', 'Application processing delay',
       'Unsolicited issuance of credit card', 'Other transaction issues',
       'Taking out the loan or lease', 'Bankruptcy',
       'Advertising and marketing', 'Account terms and changes',
       'Managing the line of credit', 'Convenience checks',
       "Can't stop charges to bank account",
       'Payment to acct not credited', 'Balance transfer',
       'Customer service/Customer relations',
       'Managing, opening, or closing account',
       'Credit monitoring or identity protection',
       'Lender repossessed or sold the vehicle', 'Other service issues',
       "Received a loan I didn't apply for", 'Disclosures', 'Privacy',
       'Overdraft, savings or rewards features',
       'Shopping for a line of credit', 'Fees',
       'Charged bank acct wrong day or amt', 'Cash advance',
       'Lender damaged or destroyed vehicle', 'Unexpected/Other fees',
       'Lender sold the property', 'Balance transfer fee', 'Adding money',
       'Incorrect/missing disclosures or info',
       'Advertising, marketing or disclosures',
       'Lender damaged or destroyed property'], dtype=object)

In [71]:
len(df_issue["Issue"].unique())

181

# Consumer Complaint Narrative

In [74]:
df["Consumer complaint narrative"].unique()

array([nan,
       '1. Inflated Appraisal by XXXX, XXXX Rocket Mortgage appointed XXXX, XXXX, to conduct the appraisal for my mortgage. I have substantial evidence to suggest that the property appraisal was deliberately inflated to justify a higher loan amount. This practice of inflating appraisals is a form of mortgage fraud that directly impacts the borrower by increasing the loan-to-value ratio, which can lead to financial instability and a higher likelihood of default. This is also a violation of federal law RESPA ( see Violations and Codes on last page ). \n\n2. Conflict of Interest and Deceptive Practices by Realtor My realtor, XXXX XXXX, was appointed by Rocket Mortgage and acted in the interest of Rocket Mortgage rather than in my best interest as her client. When I expressed concerns about the loan officer, XXXX XXXX, and the sudden increase in my approved loan amount from {$410000.00} to {$420000.00} ( despite higher taxes on the second property ), XXXX XXXX attempted to convince me that my concerns were unfounded and " all in my head. \'\' She frequently communicated with XXXX XXXX privately about my concerns and would subsequently try to persuade me to proceed with the transaction, regardless of the red flags I raised. Because of this, I felt pressured to sign closing documents because I thought I would be legally responsible for this property. \n\n3. Bait-and-Switch Tactics Rocket Mortgage engaged in bait-and-switch tactics by initially offering favorable loan terms, only to alter them during the closing process. When I questioned these changes and attempted to seek advice from other mortgage lenders, XXXX XXXX, my loan officer responded clearly with an attitude stating, " I did not know other companies were involved, \'\' which I interpreted as an attempt to shame me for seeking alternative advice and being knowledgeable about my options. \n\n4. Approval for a Loan Beyond My Means I was initially pre-approved for a loan amount of {$410000.00}, which was suddenly increased to {$420000.00} without a proper reassessment of my ability to repay. This practice, known as " loan churning \'\' or " equity stripping, \'\' involves approving a borrower for a higher loan amount than they can reasonably afford, often with little regard for the borrower \'s debt-to-income ( DTI ) ratio. This has resulted in a mortgage payment that is nearly half of my monthly salary, which is unsustainable and places me at high risk of financial distress and default. \n\n5. Negligent and Dismissive Behavior by Rocket Mortgage Executives When I contacted Rocket Mortgage \'s executive team with my concerns, I was met with dismissive and shaming behavior. Despite multiple recorded calls in which I sought clarification and education on the mortgage terms, I was essentially told that it was my fault for not understanding the complexities of the mortgage contract ( see call with XXXX XXXX who also sighed at me ). This treatment, combined with the negligent approval of a loan amount that exceeds a reasonable DTI ratio, has left me in a precarious financial situation. \n\n6. Legal Grounds for Rescission The practices described above constitute fraudulent misrepresentation, deceptive trade practices, and a violation of consumer protection laws. Under the Truth in Lending Act ( TILA ) and the Consumer Financial Protection Bureaus regulations, I am entitled to rescind the mortgage contract due to the fraudulent origination practices employed by Rocket Mortgage. There is no statute of limitations when it comes to fraudulent activity. Furthermore, the reckless disregard for my ability to repay the loan, as evidenced by the inflated loan approval and disregard for my DTI ratio, and blatant conflicts of interests strengthens the legal grounds for rescission. \n\nRequest for Amicable Resolution In light of these serious issues, I am requesting that Rocket Mortgage rescind my mortgage contract without penalty and return my down payment and closing cost, as well as the costs I incurred in lieu of this fraud. I have consulted with two consumer protection attorneys who advised that, to avoid the costs and complications of litigation, a demand letter might suffice in resolving this matter amicably, which I did XX/XX/24. However, it was scanned by Rocket Mortgage and I never received a call or email regarding my letter. I would also like to note for a contract like a mortgage to be legally binding, it usually requires the agreement of both parties, typically evidenced by their signatures. If a company or party does not sign a contract, it may not be enforceable, as my contract was only signed by XXXX XXXX. And, the mortgage application to FHA did not include XXXX XXXX XXXX on application, which was made aware of at closing that XXXX XXXX XXXX XXXX was not on deed. If a mortgage lender fails to include a spouse on an FHA loan application, resulting in the spouse not being listed on the deed, several legal and regulatory issues have been violated. Violations include : Truth in Lending Act ( TILA ), Equal Credit Opportunity Act ( ECOA ), Fair Housing Act, Breach of Contract, violations to adhere of FHA guidelines and negligence. \n\nI hope we can come to an agreement without involving ligation, Consumer Financial Protection, Attorney General, HUD or a judge. \n\nCalls to XXXX XXXX in Executive Office, XXXX XXXX, voicemail to XXXX XXXX on XX/XX/24. \n\n\n\nViolations of other codes, laws, policies, or procedures 2201 section 2201 statue of frauds, everything if you dont raise it, you waive it. All deeds of trust contain a confess judgment. \n\nSecurities is not a negotiable instrument have a maturity of more than nine months Title 15, section 78 C810 Rule 13 Mandatory Counterclaim UCC 3305 3306 16 CSR 432 3.106 D 226.23 of Tila 12 CFR CODE OF REGULATION Z RESPA 8-505 AND 8508 INVESTMENT CONTRACT NOT LOAN GOVERNED BY CONTRACT LAW',
       "I deposited XXXX separate checks via chase mobile app in XX/XX/year>. The total sum of checks were aprx XXXX. Chase Bank is unable to verify checks. Chase Representative state that phone number does not match the address to the maker. These checks were issued by XXXX XXXX XXXX XXXX XXXX These checks are valid and due to me. Chase Bank refused to return checks, instead it was kept, it reflects that I was paid in maker 's account, so there is no way to reissue new checks. Chase also abruptly closed the checking account. It's been 9 months and I have not received full payment. Only the initial aprx {$400.00} dollars was released when I made the deposit. I am a landlord that decided to rent out my property to a tenant, that receive XXXX XXXX XXXX XXXX and XXXX XXXX XXXX for rental assistance. The XXXX was supposed to cover rental payments from XX/XX/year> XXXX 2024. After XXXX I received monthly checks and deposited it in XXXX XXXXXXXX XXXX. Checks are actually XXXX XXXX XXXXXXXX checks and there is no issue with verification.",
       ...,
       'In accordance with the fair credit reporting act XXXX, Account numbers : XXXX, XXXX, XXXX, have violated my rights. 15 USC 1681 Section 602 states I have the right to privacy. 15 USC 1681 Section 604 A section 2 : It also states a consumer reporting agency can not furnish an account without my written instructions. 15 USC 1666B : A creditor may not treat a payment on a credit card account under an open end consumer credit plan as late for purpose.',
       'In accordance with the fair credit reporting act XXXX, Account numbers : XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, have violated my rights. \n15 USC 1681 Section 602 states I have the right to privacy.\n\n15 USC 1681 Section 604 A section 2 : It also states a consumer reporting agency can not furnish an account without my written instructions.\n\n15 USC 1666B : A creditor may not treat a payment on a credit card account under an open end consumer credit plan as late for purpose.',
       'I am a natural person, I am a living human being, I have rights under 15 USC 1681. Experian is govern by 15 USC 1681. And they violated my rights numerous of times. I demand the accounts listed below be removed because According to 15 USC 1681 : I have the right to privacy and I did not give EXPERIAN written permission to furnish these accounts listed below. XXXX XXXX XXXX XXXX XXXX'],
      dtype=object)